### ISSUE TITLE
Example - Get/Set device properties (numbers of channels, sample rate, frame size…)

### ISSUE THREAD

**Issue by samaaron** [nagachika/ruby-coreaudio#16]
Hi there,

I'd love to set the sample rate for a given `AudioDevice`. Unfortunately I couldn't figure out how to do this. Is there any chance you could add an example file showing how you can set device properties?

Thanks!

**Comment by nagachika** [comment]
Hello samaaron.

I'm so sorry for my late response.
I'll check and merge xavriley's pull request later but it seems good example for setting sampling rate.

And there's no options for numbers of channel and frame size etc... I'll investigate the way to add these options by CoreAudio API, but I cannot say it's possible or not just now.
